<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.user.provider.concrete.chain_provider' shared service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/User/UserProviderInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/User/PasswordUpgraderInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/User/ChainUserProvider.php';

return $this->privates['security.user.provider.concrete.chain_provider'] = new \Symfony\Component\Security\Core\User\ChainUserProvider(new RewindableGenerator(function () {
    yield 0 => ($this->privates['security.user.provider.concrete.member_provider'] ?? $this->load('getSecurity_User_Provider_Concrete_MemberProviderService.php'));
    yield 1 => ($this->privates['security.user.provider.concrete.partner_provider'] ?? $this->load('getSecurity_User_Provider_Concrete_PartnerProviderService.php'));
    yield 2 => ($this->privates['security.user.provider.concrete.supervisor_provider'] ?? $this->load('getSecurity_User_Provider_Concrete_SupervisorProviderService.php'));
}, 3));
